// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrORtd3k6mE4m1NAKHofeP2qA11NUaIRU',
    appId: '1:204568663112:web:2a4a222680efd0d44a747d',
    messagingSenderId: '204568663112',
    projectId: 'myownapp-2e043',
    authDomain: 'myownapp-2e043.firebaseapp.com',
    storageBucket: 'myownapp-2e043.firebasestorage.app',
    measurementId: 'G-X9D2WKLF2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrOW9LfSndtqjVbqo2gpVOKIxWZYY0ho',
    appId: '1:204568663112:android:593bc6c15033cb2b4a747d',
    messagingSenderId: '204568663112',
    projectId: 'myownapp-2e043',
    storageBucket: 'myownapp-2e043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh10J3Fjmc-LhBBm6YPi3o7OEPoC61c18',
    appId: '1:204568663112:ios:9f9b8ba34aa95d284a747d',
    messagingSenderId: '204568663112',
    projectId: 'myownapp-2e043',
    storageBucket: 'myownapp-2e043.firebasestorage.app',
    iosBundleId: 'com.example.myOwnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh10J3Fjmc-LhBBm6YPi3o7OEPoC61c18',
    appId: '1:204568663112:ios:9f9b8ba34aa95d284a747d',
    messagingSenderId: '204568663112',
    projectId: 'myownapp-2e043',
    storageBucket: 'myownapp-2e043.firebasestorage.app',
    iosBundleId: 'com.example.myOwnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrORtd3k6mE4m1NAKHofeP2qA11NUaIRU',
    appId: '1:204568663112:web:3527a212acd766ab4a747d',
    messagingSenderId: '204568663112',
    projectId: 'myownapp-2e043',
    authDomain: 'myownapp-2e043.firebaseapp.com',
    storageBucket: 'myownapp-2e043.firebasestorage.app',
    measurementId: 'G-D9YV7CTTEH',
  );
}
